spring:
 security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          facebook:
            client-id: YOUR_FACEBOOK_CLIENT_ID
            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
            scope:
              - email
              - public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
    user:
      name: user
      password: password
    config:
      order: 2147483647
    application:
      name: RedLado
      server:
        port: 6969
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

      

security:
  basic:
    enabled: false

  http:
    security:
      basic:
        enabled: false
      csrf:
        disabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
