spring:
  security:
    user:
      name: user
      password: password
    config:
      order: 2147483647

security:
  basic:
    enabled: false

http:
  security:
    basic:
      enabled: false
    csrf:
      disabled: true
